[build]
  publish = "."

[[redirects]]
  from = "/terms"
  to = "/terms.html"
  status = 200

[[redirects]]
  from = "/privacy"
  to = "/privacy.html"
  status = 200

[[redirects]]
  from = "/subprocessors"
  to = "/subprocessors.html"
  status = 200

[[redirects]]
  from = "/auth"
  to = "/auth.html"
  status = 200

[[headers]]
  for = "/downloads/*"
  [headers.values]
    Content-Disposition = "attachment"
    Cache-Control = "public, max-age=3600"
